mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('anime/', permanent=False)),
    path('japan/', include('japan.urls')),
    path('anime/', include('anime.urls')),
    path('song/', include('song.urls')),
    path('video/', include('video.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

song/urls.py
from django.urls import path
from . import views

app_name = 'song'

urlpatterns = [
    path('', views.song_list_view, name='song_list'),
    path('add', views.song_add_view, name='song_add'),
    path('add_artist', views.artist_add_view, name='song_add'),
]

video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns = [
    path('', views.video_download_get_view, name='video_download_get'),
    path('watch/', views.video_watch_view, name='video_watch'),
    path('download/', views.video_download_view, name='video_download'),
    path('add_comment_api/', views.video_add_comment_api, name='add_comment'),
    path('test/', views.video_url_change_view, name='test'),
]

video/models.py
from django.db import models
import os

from anime.models import Anime


def get_video_file_path(instance, filename):
    upload_to = f'videos/{instance.anime.id}/'

    ext = filename.split('.')[-1]
    filename = f'{instance.anime.id}_{instance.episode}.{ext}'

    return os.path.join(upload_to, filename)

class Video(models.Model):
    name       = models.CharField('動画名', max_length=200)
    video_file = models.FileField(upload_to=get_video_file_path)
    episode    = models.IntegerField('話')
    anime      = models.ForeignKey(
                        Anime,
                        on_delete = models.PROTECT,
                        verbose_name ="アニメ"
                    )

    class Meta:
        ordering = ["anime", "episode"]

    def __str__(self):
        return f'{self.anime.name}/{str(self.episode)}話'

class Comment(models.Model):
    video   = models.ForeignKey(
                Video,
                on_delete = models.PROTECT,
                verbose_name ="動画"
            )

    comment = models.CharField('コメント', max_length=1000)
    data    = models.DateField(auto_now=True)

video/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import JsonResponse

import asyncio
import time
from asgiref.sync import sync_to_async

from .youtube import download_anime
from anime.models import Anime
from .models import Video
from .db import add_comment


async def video_download_view(request):
    if request.method == 'POST':
        anime_id = request.POST.get('anime', None)

        for num in range(1, 100):
            video   = request.POST.get(f'video-{num}', None)
            episode = request.POST.get(f'video-{num}-episode', 0)
            if video is None:
                break
            async_download_anime = sync_to_async(download_anime, thread_sensitive=False)
            asyncio.create_task(async_download_anime(video, episode, anime_id))

        return redirect(f'/anime/detail?id={anime_id}')


def video_add_comment_api(request):
    video    = request.POST.get('video', 0)
    comment  = request.POST.get('comment', '')

    c = add_comment(video, comment)

    return JsonResponse({'new_comment': c.comment})


def video_download_get_view(request):
    if request.method == 'GET':
        anime_id = request.GET.get('anime_id', 0)

        videos = []
        context = {
            'animes':         Anime.objects.all(),
            'videos':         videos,
            'selected_anime': int(anime_id)
        }

    return render(request, 'video/download.html', context)

def video_watch_view(request):

    anime_id = request.GET.get('anime_id', 0)
    episode = int(request.GET.get('episode', 0))
    videos = Video.objects.filter(anime__id=anime_id)
    
    context = {
        'video_id': videos.get(episode=episode).id,
        'video':    videos.get(episode=episode).video_file.url,
        'previous': videos.get(episode=episode).video_file.url,
        'next':     videos.get(episode=episode).video_file.url,
    }

    return render(request, 'video/watch.html', context)

def video_url_change_view(request):

    videos = Video.objects.all()

    for video in videos:
        file_name = f'{video.anime}_{video.episode}.webm'
        video.video_file.name = f'videos/{video.anime.id}/{file_name}'
        video.save()

    return render(request, 'video/download.html', {})

templates/video/download.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/video_download.css' %}">
{% endblock %}

{% block content %}
<div class="row mb-5 justify-content-center">
    <div class="col-8">
        <input type="text" id="input-video-id" class="form-control">
    </div>
    <div class="col-auto">
        <button type="button" id="video-id-button" class="btn btn-primary">追加</button>
    </div>
</div>


<form method="post" action="{% url 'video:video_download' %}">
    <select class="form-select mb-3" id="anime" name="anime">
        {% for anime in animes %}
        {% if anime.id == selected_anime %}
        <option value="{{ anime.id }}" selected>{{ anime }}</option>
        {% else %}
        <option value="{{ anime.id }}">{{ anime }}</option>
        {% endif %}
        {% endfor %}
    </select>

    {% csrf_token %}
    <table class="table" id="video-donload-table">
        <thead>
            <tr>
                <th>VIDEO ID</th>
                <th>サムネイル</th>
                <th>エピソード</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>

    <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-primary">送信</button>
    </div>

</form>
{% endblock %}

{% block script %}

<script>
    $('#video-id-button').click(function () {
        const videoID = $('#input-video-id').val()
        append_tr(videoID);
        $('#input-video-id').val('')
    });

    $('#input-video-id').keydown(function(event) {
        if (event.key === 'Enter') {
            const videoID = $('#input-video-id').val()
            append_tr(videoID);
            $('#input-video-id').val('');
        }
    })

    const append_tr = (videoID) => {
        const len = $('#video-donload-table > tbody').children().length + 1;
        const anime = `video-${len}`;
        const episode = `video-${len}-episode`;

        var tr = `
            <tr>
                <td class="col-3">
                    <input type="text" id=${anime} name=${anime} class="form-control" value=${videoID} readOnly>
                </td>
                <td>
                    <img src="" class="img-fluid" alt="...">
                </td>
                <td class="col-3">
                    <input type="text" id=${episode} name=${episode} class="form-control" value=${len}>
                </td>
            </tr>
        `
        $("#video-donload-table > tbody").append(tr);
    }
</script>

{% endblock %}

templates/video/watch.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link href="https://vjs.zencdn.net/8.3.0/video-js.css" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'css/watch.css' %}">
{% endblock %}

{% block content %}
<input id="video-id" type="text" value="{{video_id}}" hidden>
<video id="my-video" class="video-js" controls data-setup="{}" playsinline>
    <source src={{video}} />
</video>
<div class="d-flex justify-content-between align-self-center mt-3">
    <button class="btn btn-outline-dark" type="button">
        <a href={{previous}}>Previous</a>
    </button>
    <p class=" fs-1"></p>
    <button class="btn btn-outline-dark" type="button">
        <a href={{next}}>Next</a>
    </button>
</div>

<section class="mb-5">
    <h3 class="heading">コメント</h3>

    <textarea class="form-control mb-3" id="commentInput" rows="3"></textarea>
    <div class="d-flex justify-content-end mb-3 mb-5">
        <button id="comment-btn" type="button" class="btn btn-primary">コメントする</button>
    </div>

    <div id="commnet-list">
        {% for c in comments %}
        <div class="card mb-3">
            <div class="card-body">
                {{c.comment}}
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}


{% block script %}
<script>window.HELP_IMPROVE_VIDEOJS = false;</script>
<script src=" https://vjs.zencdn.net/8.3.0/video.min.js"></script>
<script>
    const video_id = $('#video-id').val()

    $('#comment-btn').click(function () {
        let comment = $('#commentInput').val()

        $.ajax({
            url: '/video/add_comment_api/',
            method: 'POST',
            data: { video: video_id, comment: comment },
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                }
            },
            success: function (data) {
                console.log(data)
                $('#commnet-list').append(
                    `
                <div class="card mb-3">
                    <div class="card-body">
                        ${data['new_comment']}
                    </div>
                </div>
                `
                )
            },
            error: function (error) {
                console.error('Error:', error);
            }
        });

    });

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>
{% endblock %}